autoInstallPeers: false
peersSuffixMaxLength: 40

# Hax, to dangerously force the dep graph
# to be what we want
publicHoistPattern:
- "ember-source"
- "@glimmer/component"

peerDependencyRules:
  allowAny:
    - "typescript"
    - "ember-source"
    - "@glimmer/compiler"
    - "@glimmer/syntax"

  ignoreMissing:
    - webpack
    - rsvp


overrides:
  "@ember/test-helpers": "$@ember/test-helpers"
  "@ember/test-waiters": "$@ember/test-waiters"
  "@glimmer/component": "$@glimmer/component"
  "ember-source": "$ember-source"
  "@embroider/macros": "$@embroider/macros"
