autoInstallPeers: false
overrides:
  '@ember/test-helpers': $@ember/test-helpers
  '@ember/test-waiters': $@ember/test-waiters
  '@glimmer/component': $@glimmer/component
  ember-source: $ember-source
  '@embroider/macros': $@embroider/macros

patchedDependencies:
  ember-mobile-menu: patches/ember-mobile-menu.patch

packageExtensions:
  ember-mobile-menu:
    peerDependencies:
      '@glimmer/tracking': ''
      'ember-source': ''

peerDependencyRules:
  allowAny:
    - typescript
    - ember-source
    - '@glimmer/compiler'
    - '@glimmer/syntax'
  ignoreMissing:
    - webpack
    - rsvp
peersSuffixMaxLength: 40
publicHoistPattern:
  - ember-source
  - '@glimmer/component'
