autoInstallPeers: false
overrides:
  '@ember/test-helpers': '>= 5.2.1'
  '@ember/test-waiters': '>= 4.1.0'
  '@glimmer/component': ^2.0.0
  ember-source: 6.6.0-alpha.1
  '@embroider/macros': 1.17.3
packageExtensions:
  ember-mobile-menu:
    peerDependencies:
      '@glimmer/tracking': ''
      ember-source: ''
patchedDependencies:
  ember-mobile-menu: patches/ember-mobile-menu.patch
peerDependencyRules:
  allowAny:
    - typescript
    - ember-source
    - '@glimmer/compiler'
    - '@glimmer/syntax'
  ignoreMissing:
    - webpack
    - rsvp
peersSuffixMaxLength: 40
publicHoistPattern:
  - ember-source
  - '@glimmer/component'
